http://www.pgatour.com/players/player.08793.tiger-woods.html/performance-stats/#uber
  http://www.pgatour.com/content/pgatour/players/player.23108.matt-kuchar.html
http://www.pgatour.com/content/pgatour/players/player.27649.brandt-snedeker.html
http://www.pgatour.com/players/player.20098.stuart-appleby.html
http://www.pgatour.com/players/player.10885.robert-allenby.html
http://www.pgatour.com/players/player.22371.aaron-baddeley.html
http://www.pgatour.com/players/player.28259.sang-moon-bae.html
http://www.pgatour.com/players/player.33141.keegan-bradley.html
http://www.pgatour.com/players/player.27436.graham-delaet.html
http://www.pgatour.com/players/player.10809.jim-furyk.html